package com.gcy.mapapp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gcy.mapapp.entity.PhotoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "photo_info".
*/
public class PhotoEntityDao extends AbstractDao<PhotoEntity, Long> {

    public static final String TABLENAME = "photo_info";

    /**
     * Properties of entity PhotoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PhotoName = new Property(1, String.class, "photoName", false, "PHOTO_NAME");
        public final static Property ImagePath = new Property(2, String.class, "imagePath", false, "IMAGE_PATH");
        public final static Property TakeTime = new Property(3, String.class, "takeTime", false, "TAKE_TIME");
        public final static Property IsExist = new Property(4, boolean.class, "isExist", false, "IS_EXIST");
    }


    public PhotoEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PhotoEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"photo_info\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PHOTO_NAME\" TEXT," + // 1: photoName
                "\"IMAGE_PATH\" TEXT," + // 2: imagePath
                "\"TAKE_TIME\" TEXT," + // 3: takeTime
                "\"IS_EXIST\" INTEGER NOT NULL );"); // 4: isExist
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"photo_info\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PhotoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String photoName = entity.getPhotoName();
        if (photoName != null) {
            stmt.bindString(2, photoName);
        }
 
        String imagePath = entity.getImagePath();
        if (imagePath != null) {
            stmt.bindString(3, imagePath);
        }
 
        String takeTime = entity.getTakeTime();
        if (takeTime != null) {
            stmt.bindString(4, takeTime);
        }
        stmt.bindLong(5, entity.getIsExist() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PhotoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String photoName = entity.getPhotoName();
        if (photoName != null) {
            stmt.bindString(2, photoName);
        }
 
        String imagePath = entity.getImagePath();
        if (imagePath != null) {
            stmt.bindString(3, imagePath);
        }
 
        String takeTime = entity.getTakeTime();
        if (takeTime != null) {
            stmt.bindString(4, takeTime);
        }
        stmt.bindLong(5, entity.getIsExist() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PhotoEntity readEntity(Cursor cursor, int offset) {
        PhotoEntity entity = new PhotoEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // photoName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imagePath
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // takeTime
            cursor.getShort(offset + 4) != 0 // isExist
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PhotoEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPhotoName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImagePath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTakeTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsExist(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PhotoEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PhotoEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PhotoEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
